version: "3"

services:
  keosd:
    image: winlin/eosmainnet:v1.1.4
    command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir --http-server-address=0.0.0.0:8888
    hostname: keosd
    ports:
      - 8888:8888
    environment:
      - WALLETPORT=8888
    volumes:
      - /data/eos/mainnet:/opt/eosio/bin/data-dir