version: "3"

services:
  nodeosd:
    image: winlin/eos:DAWN-2018-04-27-ALPHA
    command: /opt/eosio/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "9876"
    environment:
      - NODEOSPORT=8888
      - WALLETPORT=8900
    volumes:
      - 'local_data_path':/opt/eosio/bin/data-dir

